#!/bin/bash

echo $(pacman -Qentq) > pacman.bak
echo $(pacman -Qemtq) > yay.bak
echo $(pacman -Qdq) > pacman-optdep.bak

cp /etc/modprobe.d/blacklist.conf dotfiles/bak/blacklist.conf.bak
cp /etc/systemd/logind.conf dotfiles/bak/logind.conf.bak
cp /etc/pulse/default.pa dotfiles/bak/default.pa
cp /etc/udev/rules.d/50-usb_power_save.rules dotfiles/bak/50-usb_power_save.rules

DATE=$(date +"%d %a %y")

cd dotfiles
git add .
git commit -am "Backup $DATE"
git push origin master
