#!/usr/bin/env bash



### Functions


shloka () {
  var=$(cat shloka.txt)
  for (( i=0; i<${#var}; i++ )); do
     sleep 0.01 | echo -ne "$(tput setaf 2)${var:$i:1}$(tput sgr 0)"
  done
  echo ""
}

install_packages () {
  # Restore packages
  sudo pacman -Syu
  cat "~/dotfiles/backup/pacman.bak" | xargs sudo pacman -S --noconfirm --needed 2> ~/packages.log 
  #sudo pacman -S --needed - < pacman.bak
}

yay() {
  # Install yay
  sudo pacman -S --needed base-devel --noconfirm
  git clone https://aur.archlinux.org/yay.git
  cd yay
  makepkg -si
  cd ..
  rm -rf yay
}
#yay --save --answerclean All --answerdiff All

check_yay() {
  sudo pacman -Q | grep yay
  echo $? > yaystatus.log
  check yaystatus.log
}

foreign_packages () {
  # Restore foreign packages
  cat "~/dotfiles/backup/yay.bak" | xargs yay -S --needed --noconfirm 2> yay.log
}
#yay -S --needed < yay.bak
#yay -S --needed --asdeps < pacmam-optdep.bak

config() {
  # Restore user config folder
  #git clone https://github.com/jd1t25/dotfiles.git
  #cd dotfiles
  stow -d ~/dotfiles/ -t ~
  cd ~/dotfiles/config
  stow --adopt -t ~/.config .config
}

check() {
  if [ -s $1 ]
    tput setaf 1; echo "Error in ${1%.*} Installed\n"
  else
    tput setaf 2; echo "Error in ${1%.*} Installed\n"
  fi
}

# Restore Conf

#cd ~/dotfiles/bak/
#cp blacklist.conf.bak /etc/modprobe.d/blacklist.conf
#cp logind.conf.bak /etc/systemd/logind.conf
#cp system.pa.bak /etc/pulse/system.pa
#cp 50-usb_power_save.rules.bak /etc/udev/rules.d/50-usb_power_save.rules 
#cp sudoers.bak /etc/sudoers

#cd ..
#cd ..

# Oh-my-zsh
#sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

#cd ~
#
#git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git \
#  ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting
#git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
#git clone https://github.com/agkozak/zsh-z $ZSH_CUSTOM/plugins/zsh-z

#echo $(pacman -Qentq) > pacman.bak
#echo $(pacman -Qemtq) > yay.bak
#echo $(pacman -Qdq) > pacman-optdep.bak

### Main

main() {
  shloka
  install_packages 1> /dev/null
  check packages.log
  yay 1> /dev/null
  yay_status
  foreign_packages 1> /dev/null
  check yay.log
  config 1> /dev/null
  echo "\n$(tput setaf 2) Configs Done"

