require("user.main")
require("user.options")
require("user.keymaps")
require("user.functions")
require("user.telescope")
require("user.treesitter")
require("user.lsp")
require("user.nvim-cmp")
-- require("user.debug")
-- require("user.autoformat")
require("user.autosave")
require("user.toggleterm")
require("user.nvimtree")
require("user.hop")
require("user.trouble")
require("user.treesitter")
require("user.dashboard")
require("user.autoclose")
require("user.indent")
