[General]
codecs-profiles-selected=Audio - CD
filedialog-path=@Variant(\0\0\0\x11\0\0\0\xf1\x66ile:///mnt/win1/Myself/Videos/Beginner's%20Guided%20Meditation/02.%20Lesson%201%20-%20Eyes%20Open%20State%20of%20Tranquility%20(WEEK%201)/08%20-%20Lesson%201%20-%20Part%202%20-%20(Eyes%20Open)%20Tranquility%20Self%20Induction%20Practice.mp4)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x16\0\0\0\x16\0\0\ai\0\0\x4!\0\0\0\x16\0\0\0\x16\0\0\ai\0\0\x4!\0\0\0\0\0\0\0\0\a\x80\0\0\0\x16\0\0\0\x16\0\0\ai\0\0\x4!)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(1876 962)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
netMRL=
size=@Size(526 423)

[RecentsMRL]
list=file:///mnt/win1/Myself/Videos/Beginner%27s%20Guided%20Meditation/02.%20Lesson%201%20-%20Eyes%20Open%20State%20of%20Tranquility%20%28WEEK%201%29/06%20-%20Lesson%201%20Introduction.mp4, file:///mnt/win1/Myself/Videos/Beginner's%20Guided%20Meditation/02.%20Lesson%201%20-%20Eyes%20Open%20State%20of%20Tranquility%20(WEEK%201)/08%20-%20Lesson%201%20-%20Part%202%20-%20(Eyes%20Open)%20Tranquility%20Self%20Induction%20Practice.mp4, file:///mnt/win1/Myself/Videos/Beginner's%20Guided%20Meditation/02.%20Lesson%201%20-%20Eyes%20Open%20State%20of%20Tranquility%20(WEEK%201)/07%20-%20Lesson%201%20-%20Part%201%20-%20(Eyes%20Open)%20Tranquility%20Guided%20Learning.mp4, file:///mnt/win2/Series/Silo%20%282023%29%20Season%201%20S01%20%281080p%20ATVP%20WEB-DL%20x265%20HEVC%2010bit%20EAC3%20Atmos%205.1%20t3nzin%29/Silo%20%282023%29%20-%20S01E03%20-%20Machines%20%281080p%20ATVP%20WEB-DL%20x265%20t3nzin%29.mkv, file:///mnt/win2/Courses/Jon%20Kabat-Zinn%20Teaches%20Mindfulness%20and%20Meditation/Jon%20Kabat-Zinn%20Teaches%20Mindfulness%20and%20Meditation/%5BTutsNode.com%5D%20-%20Jon%20Kabat-Zinn%20Teaches%20Mindfulness%20and%20Meditation/01%20Meet%20Your%20Instructor.mkv
times=0, 384500, 0, -1, -1
