[FileDialog]
history=file:///home/jd1t/Downloads, file:///mnt/win2/Media/Movies, file:///mnt/win2, file:///mnt/win1/Myself/Videos/Beginner's Guided Meditation/02. Lesson 1 - Eyes Open State of Tranquility (WEEK 1), file:///mnt/win2/Media/TV shows/Silo
lastVisited=file:///home/jd1t/Downloads
qtVersion=6.8.1
shortcuts=file:, file:///home/jd1t, file:///mnt/win1, file:///mnt/win2
sidebarWidth=98
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3\x8a\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x2\x9d\0\0\0\x1\0\0\0\0\0\0\0?\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\0n\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0)
viewMode=List
