#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d 1 2 3 4 5 
bspc monitor DP-0 -d 6 7 8 9 10
bspc monitor DP-0 -s DP-1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config focused_border_color "#80c484"

bscpc rule -a Firefox  border=off 

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



# Apps on Floating Mode

bspc rule -a xdman-Main state=floating


# Start Apps on specific workspace

bspc rule -a Firefox desktop='^2'
bspc rule -a brave desktop='^3'
bspc rule -a qBittorrent desktop='^7'
bspc rule -a discord desktop='^8'
bspc rule -a Org.gnome.Nautilus desktop='^4'
bspc rule -a TelegramDesktop desktop='^9'
bspc rule -a m_on_browser desktop='^10' follow=off

bspc rule -a copyq state=floating hidden=on


### Startup 

#$HOME/bin/polybar.sh
$HOME/bin/multi_monitor_script
