require("user.main")
require("user.colorscheme")
require("user.options")
require("user.fidget")
require("user.keymaps")
require("user.telescope")
require("user.comment")
require("user.toggleterm")
require("user.nvimtree")
require("user.autoclose")
-- require("user.lspformat")
require("user.luasnip")
require("user.dashboard")
-- require("user.formatonsave")
require("user.autosave")
require("user.hop")
require("user.spectre")
require("user.symbols")
require("user.trouble")
require("user.neovide")
require("user.formatter")
